import { calculateViewportLayout } from "../src/viewport";

const query = new URLSearchParams(location.search);
const android = query.get("device") === "android";
const desktop = query.get("device") === "desktop";
const capture = query.get("capture") === "1";
const dark = query.get("theme") === "dark";
const framed = query.get("frame") !== "0";
const textSize = query.get("text");
const largeText = textSize === "large";
const accessibilityText = textSize === "accessibility";
const showAttachments = query.get("attachments") === "1";
const showActions = query.get("actions") === "1";
const showHistory = query.get("history") === "1";
const showLatest = query.get("latest") === "1";
const showConfirm = query.get("confirm") === "1";
const keyboardHeight = Number(query.get("keyboardHeight")) || (android ? 355 : 334);
const deviceHeight = Number(query.get("deviceHeight")) || (android ? 915 : 844);
const safeAreaTop = Math.max(0, Number(query.get("safeTop")) || 0);
const safeAreaBottom = Math.max(0, Number(query.get("safeBottom")) || 0);
const safeAreaLeft = Math.max(0, Number(query.get("safeLeft")) || 0);
const safeAreaRight = Math.max(0, Number(query.get("safeRight")) || 0);
const toolbarHeight = android ? 56 : 54;
const root = document.querySelector<HTMLElement>(".solomon-chat-root")!;
const keyboard = document.querySelector<HTMLElement>(".keyboard")!;
const toolbar = document.querySelector<HTMLElement>(".mobile-toolbar")!;
const textarea = document.querySelector<HTMLTextAreaElement>("textarea")!;
const messages = document.querySelector<HTMLElement>(".solomon-chat-messages")!;
const toggle = document.querySelector<HTMLButtonElement>("#keyboard-toggle")!;
const metrics = document.querySelector<HTMLElement>("#metrics")!;
document.body.classList.toggle("is-capture", capture);
document.body.classList.toggle("is-desktop", desktop);
document.body.classList.toggle("is-phone-capture", capture && !desktop && framed);
document.body.classList.toggle("is-unframed", capture && !desktop && !framed);
document.body.classList.toggle("theme-dark", dark);
document.body.classList.toggle("is-large-text", largeText);
document.body.classList.toggle("is-accessibility-text", accessibilityText);
root.classList.toggle("is-mobile", !desktop);
root.style.setProperty("--solomon-safe-area-top", `${safeAreaTop}px`);
root.style.setProperty("--solomon-safe-area-bottom", `${safeAreaBottom}px`);
root.style.setProperty("--solomon-safe-area-left", `${safeAreaLeft}px`);
root.style.setProperty("--solomon-safe-area-right", `${safeAreaRight}px`);
document.querySelector<HTMLElement>(".solomon-chat-attachment-tray")!.classList.toggle("is-visible", showAttachments);
document.querySelector<HTMLElement>(".solomon-chat-message:last-of-type")?.classList.toggle("is-actions-visible", showActions);
document.querySelector<HTMLElement>(".solomon-chat-load-earlier")!.hidden = !showHistory;
const latest = document.querySelector<HTMLButtonElement>(".solomon-chat-jump-latest")!;
latest.classList.toggle("is-visible", showLatest); latest.tabIndex = showLatest ? 0 : -1; latest.ariaHidden = String(!showLatest);
root.classList.toggle("has-latest", showLatest);
document.querySelector<HTMLElement>(".harness-modal-layer")!.hidden = !showConfirm;
keyboard.style.height = `${Math.max(0, keyboardHeight - (android ? 24 : 0))}px`;
document.querySelector<HTMLElement>("#device-label")!.textContent = desktop ? "Desktop" : android ? "Pixel 9" : "iPhone 15";
let open = query.get("keyboard") === "open";

function render(): void {
  const visibleHeight = open ? deviceHeight - keyboardHeight : deviceHeight;
  const layout = calculateViewportLayout({ mobile: !desktop, focused: open, layoutHeight: deviceHeight, visualHeight: visibleHeight, visualOffsetTop: android ? 24 : 0, containerBottom: deviceHeight, closedToolbarClearance: toolbarHeight });
  root.classList.toggle("is-compose-mode", layout.composeMode);
  root.classList.toggle("is-keyboard-open", layout.keyboardOpen);
  root.style.setProperty("--solomon-bottom-clearance", `${layout.bottomClearance}px`);
  keyboard.classList.toggle("is-open", open); toolbar.style.display = open ? "none" : "flex";
  toggle.ariaPressed = String(open); toggle.textContent = open ? "Close keyboard" : "Open keyboard";
  metrics.textContent = `visual ${visibleHeight}px · clearance ${layout.bottomClearance}px · safe ${safeAreaTop}/${safeAreaRight}/${safeAreaBottom}/${safeAreaLeft}px`;
  if (open) textarea.focus(); else textarea.blur();
  messages.scrollTop = messages.scrollHeight;
}
toggle.addEventListener("click", () => { open = !open; render(); });
textarea.addEventListener("focus", () => { if (!open) { open = true; render(); } });
render();
